### ISSUE TITLE
can we migrate RTC 4.0.7 to GIT ? Is there any tool available?

### ISSUE THREAD

**Issue by anishacoggit** [rtcTo/rtc2git#102]

**Comment by WtfJoke** [comment]
Have you tried to execute the tool once? Do you experience any errors?

**Comment by rattboi** [comment]
I have tried this. It doesn't work. The lscm command in RTC 4 doesn't support "--accept-missing-changesets" for accept command. I've tried hacking that out, to no avail.

**Comment by AdamBrousseau** [comment]
--accept-missing-changesets is a relatively new addition (See #90 #91 )
I have actually found that this option degrades my history "completeness" in some cases for some components. I would remove it and see how far you get.

**Comment by dentych** [comment]
Hello.

I am using this tool with RTC4.0.7. I removed the --accept-missing-changesets, and it runs relatively fine. However, it's having trouble accepting changesets with the error: "Local file system is out of sync". I have done nothing but start the script and let it run. It'll just fail after about the 4th changeset.

I tried removing all components but 1, to see if that would help, but it didn't.

Any suggestions?

**Comment by reinhapa** [comment]
Hmm, seem's that the RTC client does not recognize all file changes. Possibly there is a refresh command available for the RTC command line tool...

Unfortunately our alternative migration implementation, written as a RTC extension does not support that old versions of RTC. :-(

**Comment by dentych** [comment]
Yeah. I'll be looking a little more into the SCM tool and see if there's any way to force the acceptance of changesets. It's SO CLOSE to working, I only need it to be able to accept changesets, then I can move my history.

I have also looked at the RTC extension. It's a shame it doesn't work for 4.0.7 :cry:

**Comment by reinhapa** [comment]
Have you tried to use the 5.0.x docker image to migrate with rtccli?

**Comment by dentych** [comment]
Actions have been taken to migrate to version 5+, but because of our infrastructure it hasn't been possible to update, unfortunately.

**Comment by reinhapa** [comment]
I mean use the 5.0.x client to migrate the 4.0.7 Database.

**Comment by WtfJoke** [comment]
> "Local file system is out of sync". I have done nothing but start the script and let it run. It'll just fail after about the 4th changeset.

Try @reinhapa  suggestion.

As alternative try you can try the following as well:
If you know on which changeset it fails (it seems you know its on the 4th), you can execute WorkspaceHandler().load() after accepting that to retrigger a reload and therefore "sync" the file-system.

**Comment by mfilipe** [comment]
@reinhapa I'm using the docker image to migrate a RTC 4.0.5. Unfortunately I am getting this error: 

>  Your client is version 5.0.1, and the server is version 4.0.5.  These versions are not compatible.

**Comment by reinhapa** [comment]
I have to check if I get the rtccli source compiled also under the version 4.0.x first - no promices..

**Comment by reinhapa** [comment]
Pushed docker images for 4.0.5 and 4.0.7 SCM clients with the [rtc2gitcli extension](https://github.com/rtcTo/rtc2gitcli). There are available [here](https://hub.docker.com/r/rtcto/rtc2git/). I suggest to give those a try using the documentation from the [rtc2git-docker README](https://github.com/rtcTo/rtc2git-docker/blob/java_plugin/README.adoc)

**Comment by dentych** [comment]
Nice, @reinhapa ! Just one question: The SOURCE_WORKSPACE and TARGET_WORKSPACE, should they both just be a workspace of the stream you wish to migrate to git, or should one of them be empty?

**Comment by mfilipe** [comment]
Maybe I did something wrong but I believe it didn't work:
```
root@227db9deab02:/var/data/target# scm migrate-to-git -r https://rtc-url/ -u user  -P password Source Target
[2016-09-23 20:49:40] Initialize RTC connection with connection timeout of 900s
[2016-09-23 20:49:50] Get full history information from RTC. This could take a large amount of time.
[2016-09-23 20:49:50] Create the list of baselines
[2016-09-23 20:49:51] Get changeset information for all baselines
[2016-09-23 20:49:51] Get list of baselines and changesets form RTC.
[2016-09-23 20:49:51] Generating Change Log start
[2016-09-23 20:49:51]     Finding Change Log Contents [0%]
[2016-09-23 20:49:51]     Resolving Work Items [14%]
[2016-09-23 20:49:51]     Resolving Paths in Change Set [42%]
[2016-09-23 20:49:51]     Resolving Contributors [85%]
[2016-09-23 20:49:51] Get list of baselines and changesets form RTC took [0]s.
[2016-09-23 20:49:51] Parse the list of baselines and changesets.
[2016-09-23 20:49:51] Incoming Changes
[2016-09-23 20:49:51] Parse the list of baselines and changesets took [0]s.
[2016-09-23 20:49:51] ********** BASELINE INFOS **********
[2016-09-23 20:49:51]   Baseline [Initial Baseline] with original name [Initial Baseline] created at [Wed Jun 17 21:23:59 UTC 2015] total number of changesets [0] will be tagged [true]
[2016-09-23 20:49:51]   Baseline [HEAD] with original name [HEAD] created at [Sun Aug 17 07:12:55 UTC 292278994] total number of changesets [0] will be tagged [false]
[2016-09-23 20:49:51] TOTAL NUMBER OF CHANGESETS [0]
[2016-09-23 20:49:51] ********** BASELINE INFOS **********
[2016-09-23 20:49:51] Filter included baselines...
[2016-09-23 20:49:51] ********** BASELINE INFOS **********
[2016-09-23 20:49:51]   Baseline [HEAD] with original name [HEAD] created at [Sun Aug 17 07:12:55 UTC 292278994] total number of changesets [0] will be tagged [false]
[2016-09-23 20:49:51] TOTAL NUMBER OF CHANGESETS [0]
[2016-09-23 20:49:51] ********** BASELINE INFOS **********
[2016-09-23 20:49:51] Start migration of tags.
[2016-09-23 20:49:52] Start migration of Tag [HEAD] [1/1]
[2016-09-23 20:49:52] Migration of tag [HEAD] [1/1] took [0] s
[2016-09-23 20:49:52] Migration took [11] s
```
The commit history in RTC is huge but I got just this in git:
```
root@227db9deab02:/var/data/target# git log
commit 42a7a95c95f033e9629699ef2eb5d9043ea19579
Author: RTC 2 git <rtc2git@rtc.to>
Date:   Fri Sep 23 20:57:38 2016 +0000

    Initial commit
```

**Comment by reinhapa** [comment]
Maybe the documentation is  a bit misleading. _Source_ is basically the starting point of the migration, meaning that you have to setup a workspace, where you place to the **first** change ever made. The _Target_ must be setup in such a way, that it follows the _Source_ workspace. After having set that up, you have to load the initial state of the _Target_ workspace using **FIRST**:

`scm load -r <uri> -u <username> -P <password> <TARGET_WORKSPACE>`

Then you start the actual migration with:

`scm migrate-to-git -r <uri> -u <username> -P <password> -m <migration.properties> <SOURCE_WORKSPACE> <TARGET_WORKSPACE>`

**Comment by mfilipe** [comment]
So far thank you very much for the support @reinhapa! 

I understood what you said, so I set the workspaces up as you explained but now I'm facing this problem:
```
[2016-09-23 23:06:20] Initialize RTC connection with connection timeout of 900s
[2016-09-23 23:06:30] Get full history information from RTC. This could take a large amount of time.
[2016-09-23 23:06:30] Create the list of baselines
[2016-09-23 23:06:31] Get changeset information for all baselines
[2016-09-23 23:06:32] Get list of baselines and changesets form RTC.
[2016-09-23 23:06:32] Generating Change Log start
[2016-09-23 23:06:32]     Finding Change Log Contents [0%]
[2016-09-23 23:06:33]     Resolving Work Items [14%]
[2016-09-23 23:06:33]     Resolving Paths in Change Set [42%]
[2016-09-23 23:06:34]     Resolving Contributors [85%]
[2016-09-23 23:06:34] Get list of baselines and changesets form RTC took [2]s.
[2016-09-23 23:06:34] Parse the list of baselines and changesets.
[2016-09-23 23:06:34] java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at to.rtc.cli.migrate.MigrateTo.getLastChangeSetUuids(MigrateTo.java:209)
	at to.rtc.cli.migrate.MigrateTo.addChangeSetInfo(MigrateTo.java:297)
	at to.rtc.cli.migrate.MigrateTo.run(MigrateTo.java:119)
	at to.rtc.cli.migrate.git.MigrateToGit.run(MigrateToGit.java:25)
	at com.ibm.team.filesystem.cli.core.AbstractSubcommand.run(AbstractSubcommand.java:51)
	at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.run(SubcommandLauncher.java:569)
	at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.doStart(SubcommandLauncher.java:365)
	at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.run(SubcommandLauncher.java:129)
	at com.ibm.team.rtc.cli.infrastructure.internal.Application.start(Application.java:41)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:369)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:620)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:575)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1408)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1384)
Migration took [15] s
Unexpected exception
com.ibm.team.rtc.cli.infrastructure.internal.core.CLIClientException: java.lang.ArrayIndexOutOfBoundsException: -1
	at com.ibm.team.filesystem.cli.core.util.StatusHelper.toCLIClientException(StatusHelper.java:717)
	at com.ibm.team.filesystem.cli.core.AbstractSubcommand.run(AbstractSubcommand.java:53)
	at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.run(SubcommandLauncher.java:569)
	at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.doStart(SubcommandLauncher.java:365)
	at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.run(SubcommandLauncher.java:129)
	at com.ibm.team.rtc.cli.infrastructure.internal.Application.start(Application.java:41)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:369)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:620)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:575)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1408)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1384)
Caused by: java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: -1
	at to.rtc.cli.migrate.MigrateTo.run(MigrateTo.java:175)
	at to.rtc.cli.migrate.git.MigrateToGit.run(MigrateToGit.java:25)
	at com.ibm.team.filesystem.cli.core.AbstractSubcommand.run(AbstractSubcommand.java:51)
	... 17 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at to.rtc.cli.migrate.MigrateTo.getLastChangeSetUuids(MigrateTo.java:209)
	at to.rtc.cli.migrate.MigrateTo.addChangeSetInfo(MigrateTo.java:297)
	at to.rtc.cli.migrate.MigrateTo.run(MigrateTo.java:119)
	... 19 more
```

The component has two baselines, one referencing to the initial state and another one to the actual state.

**Comment by reinhapa** [comment]
I fixed that [ArrayIndexOutOfBoundsException when running migrate-to-git](https://github.com/rtcTo/rtc2git-docker/issues/1) in the meantime. You should be able to pull the latest 4.0.7 docker image, that contains the fix.

**Comment by z9944x** [comment]
Hi,  we use version 4.0.3 of RTC here. The python script did not work since few commands are not supported on the scm tools 4.0.3.  Is there an easy way we can migrate our code from version 4.0.3.  Is compiling the rtc2gitcli with version 4.0.3 will work ?  Is the migration script support streams that have more than one components ? 
Thanks,
Sylvain

**Comment by WtfJoke** [comment]
> The python script did not work since few commands are not supported on the scm tools 4.0.3.

Do you know which commands?

> Is compiling the rtc2gitcli with version 4.0.3 will work ?

Maybe. Probably @reinhapa or someone else from the team can help you.

> Is the migration script support streams that have more than one components ?

Yes, both rtc2git and rtc2gitcli supports stream that have more than one component

**Comment by reinhapa** [comment]
@z9944x at the moment I did not tested the `rtc2gitcli` code against 4.0.3 jet. I can see if that does at least compile....

**Comment by z9944x** [comment]
Thanks @WtfJoke  and @reinhapa 

The command that is not available in the scm tools 4.0.3 is the "scm show attributes"

**Comment by WtfJoke** [comment]
> The command that is not available in the scm tools 4.0.3 is the "scm show attributes"

As written here in the [wiki](https://github.com/rtcTo/rtc2git/wiki/Used-Commands#initialization) its used to determine streamname.

According to this [ibm reference](https://www.ibm.com/support/knowledgecenter/SSYMRC_4.0.3/com.ibm.team.scm.doc/topics/workspace_propertylist.html) you probably can use  `scm workspace propertylist STREAMNAME` instead of scm show attributes

As alternative you can determine the streamuuid on your own and write in the config in streamname and replace the content of the following method
https://github.com/rtcTo/rtc2git/blob/develop/configuration.py#L289
with: `return streamname`

**Comment by z9944x** [comment]
Thanks @WtfJoke 

Usage of scm workspace propertylist STREAMNAME did not provide proper information for the UUID.

Changing the function collectstreamuuid and force the return of the UUID of my Stream allowed me to progress.

The script now try to use another non-existing command line feature : lscm set component and lscm set flowtarget. In fact, most of the flowtarget commands are not supported ( add, set, remove )

C:\Git_tree\rtc2git\rtc2git>python migration.py
refs/heads/_y_da8KErEeayK5HuOfLQSA
refs/heads/_y_da8KErEeayK5HuOfLQSA_branchpoint
15:47:21 - DIR \temp\myWorkingDirectory9
15:47:21 - Migration will take place in \temp\myWorkingDirectory9
Initialized empty Git repository in C:/temp/myWorkingDirectory9/TEST1.git/
15:47:21 - Repository was created in C:\temp\myWorkingDirectory9
Cloning into 'TEST1'...
warning: You appear to have cloned an empty repository.
done.
15:47:22 - Set core.ignorecase to false
Logged in to https://scm-dev.local/ccm/
15:47:37 - Get UUID of configured stream _y_da8KErEeayK5HuOfLQSA
Workspace (1006) "TEST9" successfully created
15:47:49 - Determine initial baseline of TEST RTC-Git Migration Default Component
15:47:57 - Initial baseline is: Baseline: (_WSwHoJoUEeayK5HuOfLQSA) 1 "Initial Baseline"   "Initial Baseline of Component TEST RTC-Git Migration Default Component"  Sylvain Gagn├Ü  24-Oct-2016
15:47:57 - Set component 'TEST RTC-Git Migration Default Component'(_WSuScJoUEeayK5HuOfLQSA) to baseline 'Automatically detected initial baseline' (_WSwHoJoUEeayK5HuOfLQSA)
15:47:57 - lscm set component -r https://scm-dev.local/ccm/ -b _WSwHoJoUEeayK5HuOfLQSA TEST9 stream _y_da8KErEeayK5HuOfLQSA _WSuScJoUEeayK5HuOfLQSA --overwrite-uncommitted

Usage: lscm [options] [command]

Use lscm help [command] to get detailed help for a specific command

  command - Name of the command to run

Options:
  --config arg           - Specify the location of the configuration directory.
  --no-mask              - Prevent the password entry prompt from masking the
                           user's password.
  --non-interactive      - Prevent the client from prompting for information.
  -a [--show-alias] arg  - Specify when aliases are to be shown: "y"/"yes", or
                           "n"/"no"
  -h [--help]            - Display this message.
  -u [--show-uuid] arg   - Specify when UUIDs are to be shown: "y"/"yes", or
                           "n"/"no"
  -v [--version]         - Display the version number and exit.

Commands:
  accept       - Accepts change sets into a remote workspace, and download the
                 changes.
  annotate     - Annotates lines of text file such as author, time stamp,
                 comment etc.
  baseline     - Changes attributes of a baseline.
  changeaccess - Modifies the read access permissions for files and folders.
  changeset    - Manipulates change sets.
  checkin      - Checks in changes into the current workspace, adding them to
                 the active change set.
  compare      - Compares the contents of workspaces, streams, baselines, or
                 snapshots.
  component    - Changes attributes of a component.
  conflicts    - Shows unresolved conflicts.
  create       - Creates an item.
  delete       - Deletes repository items.
  deliver      - Delivers checked in changes from a remote workspace to another
                 workspace or stream.
  diff         - Shows the changes made to a file or set of files.
  discard      - Discards change sets.
  extract      - Extracts content from the repository.
  help         - List available subcommands and provide detailed help on each.
  history      - Shows the history for a file or component.
  lastmod      - Returns the latest modification time for a folder subtree.
  list         - Lists repository items.
  load         - Loads a repository workspace onto the local file system.
  lock         - Acquires or releases locks in a stream.
  login        - Stores credentials for a repository connection.
  logout       - Deletes stored credentials.
  move         - Moves a shared resource from one location to another.
  preference   - Modifies the command line client preferences.
  property     - Modifies the properties of a file or folder.
  refresh      - Refreshes parts of the file system.
  repair       - Repairs a corrupted workspace.
  resolve      - Resolves conflicts.
  share        - Shares one or more directories.
  snapshot     - Subcommands to work with snapshots
  status       - Shows status and pending changes.
  undo         - Reverses changes to files.
  users        - Subcommands to work with user records.
  validate     - Validate sandbox metadata.
  version      - Show versioning information.
  workspace    - Changes attributes of a workspace.
Unknown subcommand:
Unknown subcommand "set"
15:47:57 - Start (re)loading current workspace: lscm load -r https://scm-dev.local/ccm/ TEST9 --force
Successfully loaded items into the sandbox.
15:48:19 - Load of workspace finished
15:48:19 - Push of branch master
Counting objects: 3, done.
Writing objects: 100% (3/3), 245 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
To C:/temp/myWorkingDirectory9/TEST1.git
- [new branch]      master -> master
  15:48:25 - Set new Flowtargets
  15:48:30 - lscm set flowtarget -r https://scm-dev.local/ccm/ TEST9 --default --current _y_da8KErEeayK5HuOfLQSA

Usage: lscm [options] [command]

Use lscm help [command] to get detailed help for a specific command

  command - Name of the command to run

Options:
  --config arg           - Specify the location of the configuration directory.
  --no-mask              - Prevent the password entry prompt from masking the
                           user's password.
  --non-interactive      - Prevent the client from prompting for information.
  -a [--show-alias] arg  - Specify when aliases are to be shown: "y"/"yes", or
                           "n"/"no"
  -h [--help]            - Display this message.
  -u [--show-uuid] arg   - Specify when UUIDs are to be shown: "y"/"yes", or
                           "n"/"no"
  -v [--version]         - Display the version number and exit.

Commands:
  accept       - Accepts change sets into a remote workspace, and download the
                 changes.
  annotate     - Annotates lines of text file such as author, time stamp,
                 comment etc.
  baseline     - Changes attributes of a baseline.
  changeaccess - Modifies the read access permissions for files and folders.
  changeset    - Manipulates change sets.
  checkin      - Checks in changes into the current workspace, adding them to
                 the active change set.
  compare      - Compares the contents of workspaces, streams, baselines, or
                 snapshots.
  component    - Changes attributes of a component.
  conflicts    - Shows unresolved conflicts.
  create       - Creates an item.
  delete       - Deletes repository items.
  deliver      - Delivers checked in changes from a remote workspace to another
                 workspace or stream.
  diff         - Shows the changes made to a file or set of files.
  discard      - Discards change sets.
  extract      - Extracts content from the repository.
  help         - List available subcommands and provide detailed help on each.
  history      - Shows the history for a file or component.
  lastmod      - Returns the latest modification time for a folder subtree.
  list         - Lists repository items.
  load         - Loads a repository workspace onto the local file system.
  lock         - Acquires or releases locks in a stream.
  login        - Stores credentials for a repository connection.
  logout       - Deletes stored credentials.
  move         - Moves a shared resource from one location to another.
  preference   - Modifies the command line client preferences.
  property     - Modifies the properties of a file or folder.
  refresh      - Refreshes parts of the file system.
  repair       - Repairs a corrupted workspace.
  resolve      - Resolves conflicts.
  share        - Shares one or more directories.
  snapshot     - Subcommands to work with snapshots
  status       - Shows status and pending changes.
  undo         - Reverses changes to files.
  users        - Subcommands to work with user records.
  validate     - Validate sandbox metadata.
  version      - Show versioning information.
  workspace    - Changes attributes of a workspace.
Unknown subcommand:
Unknown subcommand "set"
15:48:31 - Warning - UseProvidedHistory is set to false, merge-conflicts are more likely to happen.
 For more information see https://github.com/rtcTo/rtc2git/wiki/Getting-your-History-Files
15:48:31 - Start collecting changeentries
15:48:31 - Collect changes until baseline test of component TEST RTC-Git Migration Default Component
Switched to a new branch '_y_da8KErEeayK5HuOfLQSA'
15:48:41 - Start collecting changes since baseline creation
11/02/16 15:48:52 - Start accepting 0 changesets
Successfully logged out of https://scm-dev.local/ccm/
15:48:57 -
All changes accepted - Migration of stream '_y_da8KErEeayK5HuOfLQSA' is completed.
You can distribute the git-repo 'TEST1.git'.

**Comment by WtfJoke** [comment]
I used this reference:
http://www.ibm.com/support/knowledgecenter/SSCP65_4.0.3/com.ibm.team.scm.doc/topics/workspace_replace-components.html

>  lscm set component

will be
`lscm workspace replace-components`

and 

> lscm set flowtarget

will probably be:
`lscm workspace flowtarget [options] <workspace><target-workspace>`

**Comment by z9944x** [comment]
Thanks @WtfJoke 
I made the changes in addition remove the option --accept-missing-changesets from the accept command, and the script ran completely.  The git history seem correct but i did not see rtc baseline converted as a tag in git.  Is this assumption that baseline = tag in git is correct ?

**Comment by WtfJoke** [comment]
> Thanks @WtfJoke
> I made the changes in addition remove the option --accept-missing-changesets from the accept command, and the script ran completely. 

Cool :) Happy to help.

> The git history seem correct but i did not see rtc baseline converted as a tag in git. Is this assumption that baseline = tag in git is correct ?

The script doesnt support the conversion of baselines to git tags.
Where [rtc2gitcli](https://github.com/rtcTo/rtc2gitcli) or the [available docker-image of rtc2gitcli](https://hub.docker.com/r/rtcto/rtc2git/tags/) does support this feature.

EDIT: @z9944x : Can you please open up a pull request to branch 4.0? So others can reuse your adjustments.
