### ISSUE TITLE
Error: "destination path 'XXX' already exists and is not an empty directory

### ISSUE THREAD

**Issue by hachillesIBM** [rtcTo/rtc2git#103]
Hi,
I'm trying to migrate an RTC repository to git using the tools..  I've set up the config.ini file & when I run the migration.py script I get the following error:
    "fatal: destination path 'IWM_m4' already exists and is not an empty directory.

IWM_m4 is the "git-Reponame' in the config.ini script..  this repo did not exist before I ran the migration script.. so I'm not sure why I am seeing this error..  THere is a cut & paste of the logging below (I added a couple logging lines to see some info)
Any insights/suggestions are appreciated.
===============
./migration.py
 
refs/heads/rtc_migration1
refs/heads/rtc_migration1_branchpoint
13:46:32 - Migration will take place in tmp/rtc_migration_tmp
Initialized empty Git repository in /Users/heather_achilles/GitHub/rtc2git/tmp/rtc_migration_tmp/IWM_m4/
13:46:32 - Repository was created in /Users/heather_achilles/GitHub/rtc2git/tmp/rtc_migration_tmp
fatal: destination path 'IWM_m4' already exists and is not an empty directory.
13:46:32 - cloned Repo Name IW
13:46:32 - Repo Name IWM_m4
Traceback (most recent call last):
  File "./migration.py", line 169, in <module>
    migrate()
  File "./migration.py", line 63, in migrate
    initialize()
  File "./migration.py", line 27, in initialize
    git.initalize()
  File "/Users/heather_achilles/GitHub/rtc2git/gitFunctions.py", line 53, in initalize
    self.createrepo()
  File "/Users/heather_achilles/GitHub/rtc2git/gitFunctions.py", line 68, in createrepo
    os.chdir(self.clonedRepoName)
FileNotFoundError: [Errno 2] No such file or directory: 'IW'

**Comment by hachillesIBM** [comment]
looks like the problem is that the repo name needs a  ".git" ..  adding that extension allowed me to get by this error.  Thanks!
